name:                type-sets
version:             0.1.0.0
github:              "isovector/type-sets"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Type-level sets
category:            Type

description:         Please see the README on GitHub at <https://github.com/isovector/type-sets#readme>

dependencies:
- base >= 4.7 && < 5
- cmptype ^>= 0.1.0.0

library:
  source-dirs: src

tests:
  type-sets-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - type-sets
