name:                magic-tyfams
version:             0.1.1.0
github:              "https://github.com/isovector/type-sets/tree/master/magic-tyfams"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Write plugins for magic type families with ease
category:            Compiler Plugin

description:         Please see the README on GitHub at <https://github.com/isovector/type-sets/tree/master/magic-tyfams#readme>

dependencies:
- base >= 4.7 && < 5
- ghc >= 8.6.3 && < 8.8
- ghc-tcplugins-extra ^>= 0.3
- syb ^>= 0.7

library:
  source-dirs: src

